### ISSUE TITLE
Customer verification endpoint

### ISSUE THREAD

**Issue by o4codes** [Skill4Cash/Skill4Cash-BE#12]

**Comment by paisoncodes** [comment]
what verification??
email or text?

**Comment by paisoncodes** [comment]
and also send me the details on slack...

**Comment by o4codes** [comment]
The verification details for customers should be discussed with Sammy.
If you can go ahead with service provider verification it would be nice.
Kindly use the figma design to understand the service provider verification.

@paisoncodes

**Comment by paisoncodes** [comment]
okay, I have the code ready. should I just push and you test it from heroku?
@o4codes

**Comment by paisoncodes** [comment]
okay... I think it's going to be the same process for both service providers and customers. right?
@o4codes

**Comment by o4codes** [comment]
Service provider has a 2 step verification.
The first step is email verification.
The next step is document verification.

Customers just has email verification.

Therefore,  the email verification is the same for both entities.

**Comment by paisoncodes** [comment]
I've completed this and made a pr please check and merge. Also, there's a pr there by @noornee.
@o4codes
